In [1]:
import pandas as pd 
from bs4 import BeautifulSoup
import requests

In [2]:
url='https://taxfoundation.org/data/all/federal/2025-tax-brackets/'
page=requests.get(url)
page

In [3]:
soup=BeautifulSoup(page.content,'html.parser')
soup
table=soup.find_all('table')[0]  
table

<table aria-describedby="tablepress-703-description" aria-labelledby="tablepress-703-name" class="tablepress tablepress-id-703 tablepress-responsive" id="tablepress-703">
<thead>
<tr class="row-1">
<th class="column-1"><strong>Tax Rate</strong></th><th class="column-2"><strong>For Single Filers</strong></th><th class="column-3"><strong>For Married Individuals Filing Joint Returns</strong></th><th class="column-4"><strong>For Heads of Households</strong></th>
</tr>
</thead>
<tbody class="row-striping row-hover">
<tr class="row-2">
<td class="column-1">10%</td><td class="column-2">$0 to $11,925</td><td class="column-3">$0 to $23,850</td><td class="column-4">$0 to $17,000</td>
</tr>
<tr class="row-3">
<td class="column-1">12%</td><td class="column-2">$11,925 to $48,475</td><td class="column-3">$23,850 to $96,950</td><td class="column-4">$17,000 to $64,850</td>
</tr>
<tr class="row-4">
<td class="column-1">22%</td><td class="column-2">$48,475 to $103,350</td><td class="column-3">$96,950 to $206,700</td><td class="column-4">$64,850 to $103,350</td>
</tr>
<tr class="row-5">
<td class="column-1">24%</td><td class="column-2">$103,350 to $197,300</td><td class="column-3">$206,700 to $394,600</td><td class="column-4">$103,350 to $197,300</td>
</tr>
<tr class="row-6">
<td class="column-1">32%</td><td class="column-2">$197,300 to $250,525</td><td class="column-3">$394,600 to $501,050</td><td class="column-4">$197,300 to $250,500</td>
</tr>
<tr class="row-7">
<td class="column-1">35%</td><td class="column-2">$250,525 to $626,350</td><td class="column-3">$501,050 to $751,600</td><td class="column-4">$250,500 to $626,350</td>
</tr>
<tr class="row-8">
<td class="column-1">37%</td><td class="column-2">$626,350 or more</td><td class="column-3">$751,600 or more</td><td class="column-4">$626,350 or more</td>
</tr>
</tbody>
</table>

In [4]:
table_indexing = table.find_all('th')
table_indexing
table_indexing_title = [title.text.strip() for title in table_indexing]
table_indexing_title

['Tax Rate',
 'For Single\xa0Filers',
 'For Married Individuals Filing Joint Returns',
 'For Heads of Households']

In [5]:
df=pd.DataFrame(columns=table_indexing_title)
df

Empty DataFrame
Columns: [Tax Rate, For Single Filers, For Married Individuals Filing Joint Returns, For Heads of Households]
Index: []

In [6]:
column_rows = table.find_all('tr')
for row in column_rows[1:]:
    row_contents= row.find_all('td')
    data_row = [data.text.strip() for data in row_contents]
    df.loc[len(df)]= data_row
df

,Tax Rate,For Single Filers,For Married Individuals Filing Joint Returns,For Heads of Households
0,10%,"$0 to $11,925","$0 to $23,850","$0 to $17,000"
1,12%,"$11,925 to $48,475","$23,850 to $96,950","$17,000 to $64,850"
2,22%,"$48,475 to $103,350","$96,950 to $206,700","$64,850 to $103,350"
3,24%,"$103,350 to $197,300","$206,700 to $394,600","$103,350 to $197,300"
4,32%,"$197,300 to $250,525","$394,600 to $501,050","$197,300 to $250,500"
5,35%,"$250,525 to $626,350","$501,050 to $751,600","$250,500 to $626,350"
6,37%,"$626,350 or more","$751,600 or more","$626,350 or more"

In [ ]:
table2=soup.find_all('table',id='tablepress-707')[0]
table2
table2_indexing = table2.find_all('th')
table2_indexing_title = [title.text.strip() for title in table2_indexing]
df2=pd.DataFrame(columns=table2_indexing_title)
df2

Empty DataFrame
Columns: [Filing Status, , No Children, One Child, Two Children, Three or More Children]
Index: []

In [16]:
column_rows=table2.find_all('tr')
for row in column_rows[1:]:
    row_contents=row.find_all('td')
    data_row=[data.text.strip() for data in row_contents]
    df2.loc[len(df2)]=data_row
df2

,Filing Status,,No Children,One Child,Two Children,Three or More Children
0,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
1,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
2,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
3,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
4,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
5,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
6,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
7,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
8,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
9,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
10,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
11,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
12,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
13,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
14,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
15,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
16,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
17,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
18,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
19,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
20,Single or Head of Household,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
21,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
22,,Phaseout Begins,"$10,620","$23,350","$23,350","$23,350"
23,,Phaseout Ends (Credit Equals Zero),"$19,104","$50,434","$57,310","$61,555"
24,,,,,,
25,Married Filing Jointly,Income at Max Credit,"$8,490","$12,730","$17,880","$17,880"
26,,Maximum Credit,$649,"$4,328","$7,152","$8,046"
27,,Phaseout Begins,"$17,730","$30,470","$30,470","$30,470"
28,,Phaseout Ends (Credit Equals Zero),"$26,214","$57,554","$64,430","$68,675"